feat: add posting terminal app with configuration across config and nvim

diff --git a/home/.chezmoiscripts/darwin/run_after_install-packages.sh.tmpl b/home/.chezmoiscripts/darwin/run_after_install-packages.sh.tmpl
--- a/home/.chezmoiscripts/darwin/run_after_install-packages.sh.tmpl
+++ b/home/.chezmoiscripts/darwin/run_after_install-packages.sh.tmpl
@@ -31,28 +31,34 @@ function install_gh_extensions() {
 }
 
 function install_xterm_kitty_terminfo() {
-    # Attempt to get terminfo for xterm-kitty
-    if ! infocmp xterm-kitty &>/dev/null; then
-      echo "xterm-kitty terminfo not found. Installing..."
-      # Create a temp file
-      tempfile=$(mktemp)
-      # Download the kitty.terminfo file
-      # https://github.com/kovidgoyal/kitty/blob/master/terminfo/kitty.terminfo
-      if curl -o "$tempfile" https://raw.githubusercontent.com/kovidgoyal/kitty/master/terminfo/kitty.terminfo; then
-        echo "Downloaded kitty.terminfo successfully."
-        # Compile and install the terminfo entry for my current user
-        if tic -x -o ~/.terminfo "$tempfile"; then
-          echo "xterm-kitty terminfo installed successfully."
-        else
-          echo "Failed to compile and install xterm-kitty terminfo."
-        fi
+  # Attempt to get terminfo for xterm-kitty
+  if ! infocmp xterm-kitty &>/dev/null; then
+    echo "xterm-kitty terminfo not found. Installing..."
+    # Create a temp file
+    tempfile=$(mktemp)
+    # Download the kitty.terminfo file
+    # https://github.com/kovidgoyal/kitty/blob/master/terminfo/kitty.terminfo
+    if curl -o "$tempfile" https://raw.githubusercontent.com/kovidgoyal/kitty/master/terminfo/kitty.terminfo; then
+      echo "Downloaded kitty.terminfo successfully."
+      # Compile and install the terminfo entry for my current user
+      if tic -x -o ~/.terminfo "$tempfile"; then
+        echo "xterm-kitty terminfo installed successfully."
       else
-        echo "Failed to download kitty.terminfo."
+        echo "Failed to compile and install xterm-kitty terminfo."
       fi
-      # Remove the temporary file
-      rm "$tempfile"
+    else
+      echo "Failed to download kitty.terminfo."
     fi
-  }
+    # Remove the temporary file
+    rm "$tempfile"
+  fi
+}
+
+function install_uv_tools() {
+  {{ range .uv_tools }}
+    uv tool install {{ . }}
+  {{ end }}
+}
 
 function main() {
   brew_bundle
